version: '3.8'

services:

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  backend:
    build: ./backend/resume
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - mongo
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    volumes:
      - ./uploads:/app/uploads   # ✅ FIXED

  frontend:
    build: ./frontend/resume-frontend
    container_name: frontend
    ports:
      - "4200:80"
    depends_on:
      - backend

volumes:
  mongo-data: